[33mWARNING[0m:  [03-09-2024 21:21:57] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[33mWARNING[0m:  [03-09-2024 21:22:36] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[33mWARNING[0m:  [03-09-2024 21:22:49] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[33mWARNING[0m:  [03-09-2024 21:23:07] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[32mINFO[0m:     [03-09-2024 21:23:07] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [03-09-2024 21:23:07] Starting component System
[36mDEBUG[0m:    [03-09-2024 21:23:07] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [03-09-2024 21:23:07] Starting component SqliteDB
[36mDEBUG[0m:    [03-09-2024 21:23:07] Starting component QuotaEnforcer
[36mDEBUG[0m:    [03-09-2024 21:23:07] Starting component Posthog
[36mDEBUG[0m:    [03-09-2024 21:23:07] Starting component LocalSegmentManager
[36mDEBUG[0m:    [03-09-2024 21:23:07] Starting component SegmentAPI
[32mINFO[0m:     [03-09-2024 21:23:07] Started server process [[36m88323[0m]
[32mINFO[0m:     [03-09-2024 21:23:07] Waiting for application startup.
[32mINFO[0m:     [03-09-2024 21:23:07] Application startup complete.
[32mINFO[0m:     [03-09-2024 21:23:07] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [03-09-2024 21:23:14] Shutting down
[32mINFO[0m:     [03-09-2024 21:23:14] Waiting for application shutdown.
[36mDEBUG[0m:    [03-09-2024 21:23:14] Stopping component System
[36mDEBUG[0m:    [03-09-2024 21:23:14] Stopping component SegmentAPI
[36mDEBUG[0m:    [03-09-2024 21:23:14] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [03-09-2024 21:23:14] Stopping component Posthog
[36mDEBUG[0m:    [03-09-2024 21:23:14] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [03-09-2024 21:23:14] Stopping component SqliteDB
[36mDEBUG[0m:    [03-09-2024 21:23:14] Stopping component OpenTelemetryClient
[32mINFO[0m:     [03-09-2024 21:23:14] Application shutdown complete.
[32mINFO[0m:     [03-09-2024 21:23:14] Finished server process [[36m88323[0m]
[33mWARNING[0m:  [03-09-2024 21:23:25] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[32mINFO[0m:     [03-09-2024 21:23:25] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [03-09-2024 21:23:25] Starting component System
[36mDEBUG[0m:    [03-09-2024 21:23:25] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [03-09-2024 21:23:25] Starting component SqliteDB
[36mDEBUG[0m:    [03-09-2024 21:23:25] Starting component QuotaEnforcer
[36mDEBUG[0m:    [03-09-2024 21:23:25] Starting component Posthog
[36mDEBUG[0m:    [03-09-2024 21:23:25] Starting component LocalSegmentManager
[36mDEBUG[0m:    [03-09-2024 21:23:25] Starting component SegmentAPI
[32mINFO[0m:     [03-09-2024 21:23:25] Started server process [[36m88746[0m]
[32mINFO[0m:     [03-09-2024 21:23:25] Waiting for application startup.
[32mINFO[0m:     [03-09-2024 21:23:25] Application startup complete.
[32mINFO[0m:     [03-09-2024 21:23:25] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [03-09-2024 21:23:59] Shutting down
[32mINFO[0m:     [03-09-2024 21:23:59] Waiting for application shutdown.
[36mDEBUG[0m:    [03-09-2024 21:23:59] Stopping component System
[36mDEBUG[0m:    [03-09-2024 21:23:59] Stopping component SegmentAPI
[36mDEBUG[0m:    [03-09-2024 21:23:59] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [03-09-2024 21:23:59] Stopping component Posthog
[36mDEBUG[0m:    [03-09-2024 21:23:59] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [03-09-2024 21:23:59] Stopping component SqliteDB
[36mDEBUG[0m:    [03-09-2024 21:23:59] Stopping component OpenTelemetryClient
[32mINFO[0m:     [03-09-2024 21:23:59] Application shutdown complete.
[32mINFO[0m:     [03-09-2024 21:23:59] Finished server process [[36m88746[0m]
[33mWARNING[0m:  [03-09-2024 21:24:04] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[32mINFO[0m:     [03-09-2024 21:24:04] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [03-09-2024 21:24:04] Starting component System
[36mDEBUG[0m:    [03-09-2024 21:24:04] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [03-09-2024 21:24:04] Starting component SqliteDB
[36mDEBUG[0m:    [03-09-2024 21:24:04] Starting component QuotaEnforcer
[36mDEBUG[0m:    [03-09-2024 21:24:04] Starting component Posthog
[36mDEBUG[0m:    [03-09-2024 21:24:04] Starting component LocalSegmentManager
[36mDEBUG[0m:    [03-09-2024 21:24:04] Starting component SegmentAPI
[32mINFO[0m:     [03-09-2024 21:24:04] Started server process [[36m89609[0m]
[32mINFO[0m:     [03-09-2024 21:24:04] Waiting for application startup.
[32mINFO[0m:     [03-09-2024 21:24:04] Application startup complete.
[32mINFO[0m:     [03-09-2024 21:24:04] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [04-09-2024 01:30:19] Shutting down
[32mINFO[0m:     [04-09-2024 01:30:19] Waiting for application shutdown.
[36mDEBUG[0m:    [04-09-2024 01:30:19] Stopping component System
[36mDEBUG[0m:    [04-09-2024 01:30:19] Stopping component SegmentAPI
[36mDEBUG[0m:    [04-09-2024 01:30:19] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [04-09-2024 01:30:19] Stopping component Posthog
[36mDEBUG[0m:    [04-09-2024 01:30:19] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [04-09-2024 01:30:19] Stopping component SqliteDB
[36mDEBUG[0m:    [04-09-2024 01:30:19] Stopping component OpenTelemetryClient
[32mINFO[0m:     [04-09-2024 01:30:19] Application shutdown complete.
[32mINFO[0m:     [04-09-2024 01:30:19] Finished server process [[36m89609[0m]
[33mWARNING[0m:  [04-09-2024 01:30:24] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[32mINFO[0m:     [04-09-2024 01:30:24] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [04-09-2024 01:30:24] Starting component System
[36mDEBUG[0m:    [04-09-2024 01:30:24] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [04-09-2024 01:30:24] Starting component SqliteDB
[36mDEBUG[0m:    [04-09-2024 01:30:24] Starting component QuotaEnforcer
[36mDEBUG[0m:    [04-09-2024 01:30:24] Starting component Posthog
[36mDEBUG[0m:    [04-09-2024 01:30:24] Starting component LocalSegmentManager
[36mDEBUG[0m:    [04-09-2024 01:30:24] Starting component SegmentAPI
[32mINFO[0m:     [04-09-2024 01:30:24] Started server process [[36m3738[0m]
[32mINFO[0m:     [04-09-2024 01:30:24] Waiting for application startup.
[32mINFO[0m:     [04-09-2024 01:30:24] Application startup complete.
[32mINFO[0m:     [04-09-2024 01:30:24] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[31mERROR[0m:    [04-09-2024 01:30:45] Expected metadata to be a non-empty dict, got 0 metadata attributes
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 105, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 118, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
  File "/opt/miniconda3/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    raise exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/fastapi/routing.py", line 297, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/fastapi/routing.py", line 210, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 630, in create_collection
    await to_thread.run_sync(
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 620, in process_create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/api/segment.py", line 166, in create_collection
    validate_metadata(metadata)
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/api/types.py", line 268, in validate_metadata
    raise ValueError(
ValueError: Expected metadata to be a non-empty dict, got 0 metadata attributes
[32mINFO[0m:     [04-09-2024 01:30:45] 127.0.0.1:54268 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [04-09-2024 01:32:34] 127.0.0.1:54360 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[31mERROR[0m:    [04-09-2024 01:34:03] Collection my_collection already exists
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 105, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 118, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
  File "/opt/miniconda3/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    raise exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/fastapi/routing.py", line 297, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/fastapi/routing.py", line 210, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 630, in create_collection
    await to_thread.run_sync(
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 620, in process_create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/api/segment.py", line 173, in create_collection
    coll, created = self._sysdb.create_collection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/db/mixins/sysdb.py", line 220, in create_collection
    raise UniqueConstraintError(f"Collection {name} already exists")
chromadb.db.base.UniqueConstraintError: Collection my_collection already exists
[32mINFO[0m:     [04-09-2024 01:34:03] 127.0.0.1:54383 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 500
[31mERROR[0m:    [04-09-2024 01:34:31] Collection my_collection already exists
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 105, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 118, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/streams/memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
  File "/opt/miniconda3/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    raise exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/miniconda3/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/fastapi/routing.py", line 297, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/fastapi/routing.py", line 210, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 630, in create_collection
    await to_thread.run_sync(
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 620, in process_create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/api/segment.py", line 173, in create_collection
    coll, created = self._sysdb.create_collection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/chromadb/db/mixins/sysdb.py", line 220, in create_collection
    raise UniqueConstraintError(f"Collection {name} already exists")
chromadb.db.base.UniqueConstraintError: Collection my_collection already exists
[32mINFO[0m:     [04-09-2024 01:34:31] 127.0.0.1:54388 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [04-09-2024 01:34:54] 127.0.0.1:54400 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 01:35:08] 127.0.0.1:54404 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 01:35:52] 127.0.0.1:54416 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 05:41:43] 127.0.0.1:58040 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 05:41:44] 127.0.0.1:58041 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 05:42:53] 127.0.0.1:58050 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 05:43:44] 127.0.0.1:58057 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 05:45:44] 127.0.0.1:58080 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 05:51:44] 127.0.0.1:59061 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 05:52:05] 127.0.0.1:59065 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 05:52:54] 127.0.0.1:59074 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 05:56:11] 127.0.0.1:59146 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 05:57:34] 127.0.0.1:59178 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 06:02:43] 127.0.0.1:59234 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 06:06:55] 127.0.0.1:59286 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 06:08:05] 127.0.0.1:59294 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 06:11:38] 127.0.0.1:59340 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 06:12:23] 127.0.0.1:59350 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 06:16:17] 127.0.0.1:59385 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 06:16:26] 127.0.0.1:59390 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 06:19:44] 127.0.0.1:59416 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 06:28:25] 127.0.0.1:59499 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 06:29:52] 127.0.0.1:59520 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 06:31:00] 127.0.0.1:59532 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 06:38:07] 127.0.0.1:59599 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[36mDEBUG[0m:    [04-09-2024 06:38:07] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [04-09-2024 06:38:07] 127.0.0.1:59599 - "POST /api/v1/collections/2ea270c1-ab01-459c-8ce0-bfe932abbeb5/add HTTP/1.1" 201
[32mINFO[0m:     [04-09-2024 07:01:34] ::1:60087 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 07:01:35] ::1:60087 - "POST /api/v1/collections/2ea270c1-ab01-459c-8ce0-bfe932abbeb5/query HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 07:03:34] ::1:60113 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 07:03:35] ::1:60113 - "POST /api/v1/collections/2ea270c1-ab01-459c-8ce0-bfe932abbeb5/query HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 07:06:56] ::1:60153 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 07:06:56] ::1:60153 - "POST /api/v1/collections/2ea270c1-ab01-459c-8ce0-bfe932abbeb5/query HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 07:08:22] ::1:60173 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 07:08:23] ::1:60173 - "POST /api/v1/collections/2ea270c1-ab01-459c-8ce0-bfe932abbeb5/query HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 07:09:29] ::1:60192 - "GET /api/v1/collections/my_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-09-2024 07:09:29] ::1:60192 - "POST /api/v1/collections/2ea270c1-ab01-459c-8ce0-bfe932abbeb5/query HTTP/1.1" 200
